#!/usr/bin/env python3
"""Run the test suite and fail only when the set of failures grows.

The suite carries a set of long-standing failures (template drift, fixtures that
predate a behaviour change, tests that need an installed generator pack). Gating
CI on a fully green run would mean either fixing all of them first or not gating
at all, so this compares the failing set against a recorded baseline instead:

* a failure not in the baseline  -> exit 1 (a regression)
* a baseline failure that passes -> reported, exit 0 (prune the baseline)
* the same set                   -> exit 0

Baseline lives in tests/known_failures.txt, one node id per line.

Usage:
    python scripts/check_test_ratchet.py                # gate
    python scripts/check_test_ratchet.py --update       # rewrite the baseline
    python scripts/check_test_ratchet.py -- -x -k flow  # extra pytest args
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BASELINE = REPO_ROOT / 'tests' / 'known_failures.txt'

# Match pytest's short-summary lines only. Captured logging is echoed into the
# same stream and can start with "ERROR" too (e.g. "ERROR  root:cli.py:5733 ..."),
# so require a real test node id: a .py path, optionally with ::ids appended.
_FAILED_RE = re.compile(r'^(?:FAILED|ERROR)\s+(\S+\.py(?:::\S+)?)(?:\s|$)')


def _display(path: Path) -> str:
    """Repo-relative path when possible, absolute otherwise.

    `relative_to` raises for a path outside the repo, which the baseline can be
    when a caller or test overrides it.
    """
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def read_baseline() -> set[str]:
    if not BASELINE.is_file():
        return set()
    out: set[str] = set()
    for line in BASELINE.read_text(encoding='utf-8').splitlines():
        text = line.strip()
        if text and not text.startswith('#'):
            out.add(text)
    return out


def write_baseline(node_ids: set[str], *, total: int) -> None:
    header = [
        '# Tests known to fail on main. Generated by scripts/check_test_ratchet.py --update.',
        '#',
        '# CI fails only when a failure appears that is NOT listed here, so this file',
        '# is a ratchet: it may shrink freely, and should only grow with a deliberate',
        '# decision. Prune an entry as soon as its test passes again.',
        f'# Recorded count: {total}',
        '',
    ]
    BASELINE.write_text('\n'.join(header + sorted(node_ids)) + '\n', encoding='utf-8')


def run_pytest(extra: list[str]) -> tuple[set[str], int]:
    cmd = [sys.executable, '-m', 'pytest', '-q', '-p', 'no:randomly', *extra]
    print(f'$ {" ".join(cmd)}', flush=True)
    proc = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    stream = (proc.stdout or '') + (proc.stderr or '')
    print(stream[-4000:], flush=True)
    failures: set[str] = set()
    for line in stream.splitlines():
        m = _FAILED_RE.match(line.strip())
        if m:
            # Strip any trailing " - AssertionError: ..." detail.
            failures.add(m.group(1).split(' - ', 1)[0])
    return failures, proc.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--update', action='store_true', help='Rewrite the baseline from this run')
    parser.add_argument('pytest_args', nargs='*', help='Extra args forwarded to pytest')
    args = parser.parse_args(argv)

    failures, _rc = run_pytest(args.pytest_args)

    if args.update:
        write_baseline(failures, total=len(failures))
        print(f'\nBaseline updated: {len(failures)} known failure(s) -> {_display(BASELINE)}')
        return 0

    # An empty baseline is a fully green suite, not a missing one. Only the file
    # being absent means "no baseline recorded yet".
    if not BASELINE.is_file():
        print(
            f'\nNo baseline at {_display(BASELINE)}.\n'
            'Record one with: python scripts/check_test_ratchet.py --update'
        )
        return 1
    baseline = read_baseline()

    new = sorted(failures - baseline)
    fixed = sorted(baseline - failures)

    print('\n' + '=' * 68)
    print(f'known failures: {len(baseline)}   this run: {len(failures)}')

    if fixed:
        print(f'\n{len(fixed)} baseline failure(s) now pass -- prune them from the baseline:')
        for node in fixed:
            print(f'  - {node}')

    if new:
        print(f'\n{len(new)} NEW failure(s) -- these are regressions:')
        for node in new:
            print(f'  + {node}')
        print('\nFAIL: the failing set grew.')
        return 1

    print('\nOK: no new failures.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
